name: Install Nginx:

on:
  push:
    branches:
      - main
workflow_dispatch

jobs:
  install-nginx:
    runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v2

- name: Update and install nginx
   run: |
      sudo apt-get update
      sudo apt-get install -y nginx

- name: Start Nginx service
   run: sudo systemctl start nginx

   - name: Enable nginx to start on boot
      run: sudo systemctl enable nginx

  - name: check Nginx status
     run: sudo systemctl status nginx
